import type { Product } from './types';

const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'LED Panel 600x1200',
    article: 'LP-6012-40W',
    price: 45.99,
    stock_quantity: 7,
    incoming_quantity: 20,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=LED',
  },
  {
    id: '2',
    name: 'Acoustic Foam Board',
    article: 'AFB-50-GRY',
    price: 12.50,
    stock_quantity: 5,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=AFB',
  },
  {
    id: '3',
    name: 'Industrial Cable 3x2.5',
    article: 'IC-3X25-BLK',
    price: 2.80,
    stock_quantity: 250,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=CBL',
  },
  {
    id: '4',
    name: 'Modular Socket 16A',
    article: 'MS-16A-WHT',
    price: 8.30,
    stock_quantity: 35,
    incoming_quantity: 50,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=SCK',
  },
  {
    id: '5',
    name: 'Circuit Breaker 32A',
    article: 'CB-32A-3P',
    price: 18.75,
    stock_quantity: 3,
    incoming_quantity: 10,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=CB',
  },
  {
    id: '6',
    name: 'PVC Conduit 25mm',
    article: 'PVC-25-GRY-3M',
    price: 3.40,
    stock_quantity: 120,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=PVC',
  },
  {
    id: '7',
    name: 'Junction Box IP65',
    article: 'JB-IP65-200',
    price: 15.60,
    stock_quantity: 8,
    incoming_quantity: 15,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=JB',
  },
  {
    id: '8',
    name: 'Cable Tray 100x50',
    article: 'CT-100X50-2M',
    price: 22.90,
    stock_quantity: 18,
    incoming_quantity: 30,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=CT',
  },
  {
    id: '9',
    name: 'Terminal Block 10mm',
    article: 'TB-10MM-BLU',
    price: 0.95,
    stock_quantity: 450,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=TB',
  },
  {
    id: '10',
    name: 'Industrial Plug 32A',
    article: 'IP-32A-3P',
    price: 25.50,
    stock_quantity: 2,
    incoming_quantity: 8,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=PLG',
  },
  {
    id: '11',
    name: 'Cable Gland M20',
    article: 'CG-M20-BRS',
    price: 4.20,
    stock_quantity: 85,
    incoming_quantity: 100,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=CG',
  },
  {
    id: '12',
    name: 'DIN Rail 35mm',
    article: 'DR-35-1M',
    price: 6.80,
    stock_quantity: 42,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=DR',
  },
  {
    id: '13',
    name: 'Contactor 25A 3P',
    article: 'CT-25A-3P-24V',
    price: 32.40,
    stock_quantity: 6,
    incoming_quantity: 12,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=CNT',
  },
  {
    id: '14',
    name: 'Emergency Light LED',
    article: 'EL-LED-3W',
    price: 28.90,
    stock_quantity: 150,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=EL',
  },
  {
    id: '15',
    name: 'Weatherproof Box',
    article: 'WB-300X200',
    price: 38.75,
    stock_quantity: 9,
    incoming_quantity: 20,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=WB',
  },
  {
    id: '16',
    name: 'Cable Tie 200mm Black',
    article: 'CT-200-BLK-100',
    price: 5.60,
    stock_quantity: 28,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=ZIP',
  },
  {
    id: '17',
    name: 'Thermal Relay 5.5-8A',
    article: 'TR-558A',
    price: 19.80,
    stock_quantity: 4,
    incoming_quantity: 15,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=TR',
  },
  {
    id: '18',
    name: 'Distribution Board 12M',
    article: 'DB-12M-FLUSH',
    price: 65.00,
    stock_quantity: 180,
    incoming_quantity: 50,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=DB',
  },
  {
    id: '19',
    name: 'Busbar 3P 63A',
    article: 'BB-3P-63A',
    price: 48.30,
    stock_quantity: 15,
    incoming_quantity: 0,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=BB',
  },
  {
    id: '20',
    name: 'Motion Sensor PIR',
    article: 'PIR-360-WHT',
    price: 16.40,
    stock_quantity: 72,
    incoming_quantity: 30,
    image_url: 'https://via.placeholder.com/100/1a1a1a/ffffff?text=PIR',
  },
];

export const getProducts = async (): Promise<Product[]> => {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_PRODUCTS;
};
